# PFieldCalc.jl (pfieldcalc.m in MATLAB)
# Computes the pressure field generated by a set of wells using
# superposition from a simple radially symmetric pressure model.

module PFieldCalc

export pfieldcalc

using LinearAlgebra
using Dates

using PressureFrontCalc # Import the pressure front calculation module
using CalcST # Import the storativity and transmissivity calculation module


# Main function to calculate the pressure field
function pfieldcalc(hDV, x = nothing, y = nothing, wells = nothing, ts = nothing)
    # Default values when arguments are not provided
    if wells === nothing
        wells = 1:hDV.data[:nwells]  # Indices of wells to use
        x = hDV.plotdata[:pflot][:Xgrid]  # x locations for pressure
        y = hDV.plotdata[:pflot][:Ygrid]  # y locations for pressure
        ts = hDV.hdsldr[:value]  # years (assume all sliders are identical)
    elseif ts === nothing
        ts = hDV.hdsldr[:value]  # years (assume all sliders are identical)
    end

    # Get storativity and transmissivity
    aqthick = hDV.data[:reservoir][:vals][1] * 0.3048  # ft to meters
    S, T = calcST(hDV.data[:adv][:vals], aqthick, hDV.data[:reservoir][:vals][2] / 100, hDV.data[:reservoir][:vals][3])
    fld = zeros(size(x))  # Initialize the pressure field matrix

    # Set up well location and rate information from either variable or constant rate structures
    if hDV.data[:realWellData][:use] && haskey(hDV.data[:realWellData], :datenumBarrelsPerDay)
        # Variable rate wells
        allWellsDatenumBarrelsPerDay = hDV.data[:realWellData][:datenumBarrelsPerDay]
        Xwell = hDV.data[:realWellData][:XEasting]
        Ywell = hDV.data[:realWellData][:YNorthing]
    else
        # Constant rate wells
        allWellsDatenumBarrelsPerDay = hDV.data[:inject][:datenumBarrelsPerDay]
        Xwell = hDV.data[:inject][:vals][:, 1]
        Ywell = hDV.data[:inject][:vals][:, 2]
    end

    # Loop over each well to calculate the pressure field
    for i in wells
        xwell = Xwell[i]
        ywell = Ywell[i]
        thisWellDatenumBarrelsPerDay = allWellsDatenumBarrelsPerDay[i, 1]  # Get data for this well

        # Grid distances to well
        difflocs = (x .+ 1im * y) .- (xwell + 1im * ywell)
        R = abs.(difflocs)  # Distance to each well grid point
        rho = hDV.data[:adv][:vals][5]  # Fluid density
        g = hDV.data[:adv][:vals][6]  # Gravitational acceleration
        rmeters = R * 1e3  # Convert distance to meters

        # Only compute pressure for positive time steps
        if any(year(thisWellDatenumBarrelsPerDay[:, 1]) .<= maximum(ts))
            pfrontResult = pfront(rmeters, ts, thisWellDatenumBarrelsPerDay, S, T, rho, g)
            fld .+= pfrontResult  # Add the results for this well
        end
    end

    # Handle infinity and NaN values in the field data
    fld[isinf.(fld)] .= 0
    fld[isnan.(fld)] .= 0

    # Convert bars to psi
    fld *= 14.5  # 1 bar = 14.5 psi

    return fld
end

end  # module PFieldCalc
