% ExxonMobil Upstream Research Company 2016
% Darren Pais
% Surveillance and Optimization, Reservoir
% Induced Seisimicty Integrated Team, Drilling and Subsurface

% Compute the pressure field generated by a set of wells using
% superposition from a simple radially symmetric pressure model

% modified by Rall Walsh to take new Pfield data with variable injection
% rates.

function fld = pfieldcalc(hDV,x,y,wells,ts) %output in psi
if nargin==1
    wells = 1:1:hDV.data.nwells; %indices of wells to use
    x = hDV.plotdata.pflot.Xgrid; %x locations for pressure
    y = hDV.plotdata.pflot.Ygrid; %y locations for pressure
    ts = get(hDV.hdsldr(1),'value')  ; %years (assume all sliders are identical)
elseif nargin==4
    ts = get(hDV.hdsldr(1),'value')  ; %years (assume all sliders are identical)
end

%get storativity and transmissivity
aqthick = hDV.data.reservoir.vals(1)*0.3048 ; %ft to meters
[S , T] = calcST(hDV.data.adv.vals , aqthick , hDV.data.reservoir.vals(2)/100 , hDV.data.reservoir.vals(3)) ;
fld = 0.*x; % setup data matrix

%setup well location and rate information from either variable or constant
%rate structures 
if (isfield(hDV.data.realWellData, 'use') && hDV.data.realWellData.use) && isfield(hDV.data.realWellData,'datenumBarrelsPerDay') %variable rate
       
    allWellsDatenumBarrelsPerDay=hDV.data.realWellData.datenumBarrelsPerDay(:,1); % get data for this variable injection rate well
    Xwell=hDV.data.realWellData.XEasting; Ywell=hDV.data.realWellData.YNorthing; %location
 
else % make constant rate injection into format of variable rate data.
    allWellsDatenumBarrelsPerDay=hDV.data.inject.datenumBarrelsPerDay(:,1); % get data for this constant rate well
    Xwell=hDV.data.inject.vals(:,1); Ywell=hDV.data.inject.vals(:,2); %location
end

for i=1:1:length(wells) %loop over each well to get the field

    k=wells(i);
    xwell = Xwell(k);
    ywell = Ywell(k);
    
    thisWellDatenumBarrelsPerDay=allWellsDatenumBarrelsPerDay{k,1}; % get data for this well
    difflocs=x+1i*y - (xwell+1i*ywell) ; R=abs(difflocs) ;    %grid distances to well
    rho = hDV.data.adv.vals(5)  ;  g = hDV.data.adv.vals(6)  ; % constants
    rmeters=R*1e3 ; %meters
    
    if  any(year(thisWellDatenumBarrelsPerDay(:,1))<= max(ts) ) %only positive time
        pfrontResult = pfront(rmeters,ts,thisWellDatenumBarrelsPerDay,S,T,rho,g); % call pfront function
        fld=fld+pfrontResult ; %bars
    end
end % end cycling wells

% psi to bars for consistency, stochastic piece
%smag = hDV.data.reservoir.vals(4)/14.5 ;
%fld = fld+smag*randn(size(fld)) ;

fld(isinf(fld)) = 0 ; %remove infinity values, typically occurs when well centers exactly match a grid location
fld(isnan(fld)) = 0 ; %remove nan values, typically occurs when time at calc is less that the well start times
fld=fld*14.5; %convert to psi

end
